repos:
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 0.7.0
    hooks:
      - id: sqlfluff-lint
      - id: sqlfluff-fix

  - repo: https://github.com/fishtown-analytics/dbt-check
    rev: v0.1.0
    hooks:
      - id: dbt-check
